# Generated by Django 2.2 on 2020-02-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='last_edited',
        ),
    ]
