# Generated by Django 2.2 on 2020-02-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200221_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
