# Generated by Django 2.2 on 2020-02-23 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
